
[[constraint]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[constraint]]
  name = "github.com/docker/cli"
  version = "18.9.0"

[[constraint]]
  name = "github.com/testcontainers/testcontainers-go"
  version = "0.0.4"
