
:branch: master

== dockmoor
image:https://img.shields.io/circleci/project/github/MeneDev/dockmoor/{branch}.svg[Build Status (Circle CI), link=https://circleci.com/gh/MeneDev/dockmoor]
image:https://img.shields.io/coveralls/github/MeneDev/dockmoor/{branch}.svg[Coveralls statement coverage, link=https://coveralls.io/github/MeneDev/dockmoor]
image:https://goreportcard.com/badge/github.com/MeneDev/dockmoor[Go Report Card, https://goreportcard.com/report/github.com/MeneDev/dockmoor]
image:https://img.shields.io/github/release/MeneDev/dockmoor.svg["GitHub release",link="https://github.com/MeneDev/dockmoor/releases"]
image:https://img.shields.io/twitter/follow/MeneDev.svg?style=social&label=%40MeneDev[Follow @MeneDev on Twitter, link=https://twitter.com/MeneDev]

Manage docker image references.

== Features

*Implemented*

* find Dockerfiles
* list image references
* filter by various predicates, e.g. only untagged or `latest`

*Upcomming*

* Pin used image references to currently used version to make builds reproducible
* Find outdated image references
* Update to newer major, minor or patch version respecting SemVer

[[_examples]]
Examples
--------

[[list-command-examples]]
list command
~~~~~~~~~~~~

The single file examples all refer to https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/Dockerfile[a multi-stage build Dockerfile]

[[_list_all_image_references_with_latest_or_no_tag_from_a_specific_domain_in_file]]
List all image references with latest or no tag from a specific domain in file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can use multiple predicates to filter the matching image references. In this example the `domain` predicate is used together wih the `latest` predicate. Predicates are connected to a `conjunction`: all predicates must match.

[subs=+macros]
....
dockmoor list --domain=example.com --latest https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/Dockerfile[Dockerfile]
....

stdout:

[subs=+macros]
....
example.com/image-name:latest@sha256:2c4269d573d9fc6e9e95d5e8f3de2dd0b07c19912551f25e848415b5dd783acf
example.com/other-image
example.com/other-image:latest
....

stderr is empty +
exit code: 0

[[_list_all_image_references_in_file]]
List all image references in file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
dockmoor list https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/Dockerfile[Dockerfile]
....

stdout:

[subs=+macros]
....
image-name
image-name:latest
image-name:1.12
image-name@sha256:2c4269d573d9fc6e9e95d5e8f3de2dd0b07c19912551f25e848415b5dd783acf
docker.io/library/image-name:1.12@sha256:2c4269d573d9fc6e9e95d5e8f3de2dd0b07c19912551f25e848415b5dd783acf
docker.io/library/image-name
docker.io/library/image-name:latest
example.com/image-name:1.12
example.com/image-name:latest@sha256:2c4269d573d9fc6e9e95d5e8f3de2dd0b07c19912551f25e848415b5dd783acf
example.com/image-name@sha256:2c4269d573d9fc6e9e95d5e8f3de2dd0b07c19912551f25e848415b5dd783acf
example.com/other-image
example.com/other-image:latest
....

stderr is empty +
exit code: 0

[[_list_all_image_references_with_latest_or_no_tag_in_file]]
List all image references with latest or no tag in file
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
dockmoor list --latest https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/Dockerfile[Dockerfile]
....

stdout:

[subs=+macros]
....
image-name
image-name:latest
docker.io/library/image-name
docker.io/library/image-name:latest
example.com/image-name:latest@sha256:2c4269d573d9fc6e9e95d5e8f3de2dd0b07c19912551f25e848415b5dd783acf
example.com/other-image
example.com/other-image:latest
....

stderr is empty +
exit code: 0

[[_list_all_unpinned_image_references]]
List all unpinned image references
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
dockmoor list --unpinned https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/Dockerfile[Dockerfile]
....

stdout:

[subs=+macros]
....
image-name
image-name:latest
image-name:1.12
docker.io/library/image-name
docker.io/library/image-name:latest
example.com/image-name:1.12
example.com/other-image
example.com/other-image:latest
....

stderr is empty +
exit code: 0

[[_use_unix_find_to_list_all_unpinned_image_references]]
Use unix find to list all unpinned image references
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
find https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/[some-folder/] -type f -exec dockmoor list --unpinned {} \; | sort | uniq
....

stdout:

[subs=+macros]
....
nginx
nginx:1.15.3
nginx:latest
....

stderr is empty +
exit code: 0

[[_use_unix_find_to_list_all_image_references_with_latestno_tags]]
Use unix find to list all image references with latest/no tags
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
find https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/[some-folder/] -type f -exec dockmoor list --latest {} \; | sort | uniq
....

stdout:

[subs=+macros]
....
nginx
nginx:latest
....

stderr is empty +
exit code: 0

[[_use_unix_find_to_list_all_image_references]]
Use unix find to list all image references
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
find https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/[some-folder/] -type f -exec dockmoor list {} \; | sort | uniq
....

stdout:

[subs=+macros]
....
nginx
nginx:1.15.3
nginx:1.15.3-alpine@sha256:2c4269d573d9fc6e9e95d5e8f3de2dd0b07c19912551f25e848415b5dd783acf
nginx:latest
nginx@sha256:db5acc22920799fe387a903437eb89387607e5b3f63cf0f4472ac182d7bad644
....

stderr is empty +
exit code: 0

[[contains-command-examples]]
contains command
~~~~~~~~~~~~~~~~

[[_use_unix_find_to_list_all_files_containing_unpinned_references]]
Use unix find to list all files containing unpinned references
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
find https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/[some-folder/] -type f -exec dockmoor contains --unpinned {} \; -print
....

stdout:

[subs=+macros]
....
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-1.15.3[some-folder/Dockerfile-nginx-1.15.3]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-untagged[some-folder/Dockerfile-nginx-untagged]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-latest[some-folder/Dockerfile-nginx-latest]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/subfolder/Dockerfile-nginx-latest[some-folder/subfolder/Dockerfile-nginx-latest]
....

stderr is empty +
exit code: 0

[[_use_unix_find_to_list_all_files_containing_latestno_tags]]
Use unix find to list all files containing latest/no tags
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
find https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/[some-folder/] -type f -exec dockmoor contains --latest {} \; -print
....

stdout:

[subs=+macros]
....
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-untagged[some-folder/Dockerfile-nginx-untagged]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-latest[some-folder/Dockerfile-nginx-latest]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/subfolder/Dockerfile-nginx-latest[some-folder/subfolder/Dockerfile-nginx-latest]
....

stderr is empty +
exit code: 0

[[_use_unix_find_to_list_all_supported_files]]
Use unix find to list all supported files
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[subs=+macros]
....
find https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/[some-folder/] -type f -exec dockmoor contains {} \; -print
....

stdout:

[subs=+macros]
....
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-tagged-digest[some-folder/Dockerfile-nginx-tagged-digest]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-1.15.3[some-folder/Dockerfile-nginx-1.15.3]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-untagged[some-folder/Dockerfile-nginx-untagged]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-latest[some-folder/Dockerfile-nginx-latest]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/Dockerfile-nginx-digest[some-folder/Dockerfile-nginx-digest]
https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/subfolder/Dockerfile-nginx-latest[some-folder/subfolder/Dockerfile-nginx-latest]
....

stderr is empty +
exit code: 0

[[_test_the_format_of_a_file]]
Test the format of a file
^^^^^^^^^^^^^^^^^^^^^^^^^

The `contains` command returns with exit code 0 when an image reference was found that matches. Using the `--any` predicate allows to match any file with a supported format that contains at least one image reference.

[subs=+macros]
....
dockmoor contains https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/Dockerfile[Dockerfile]
....

stdout is empty +
stderr is empty +
exit code: 0

[subs=+macros]
....
dockmoor contains https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/some-folder/NotADockerfile[some-folder/NotADockerfile]
....

stdout is empty +
stderr is empty +
exit code: 4

[[_supported_formats]]
Supported Formats
-----------------

* https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/Dockerfile[Dockerfile] (as used by `docker build`)

[[_usage]]
Usage
-----

__________________________________________________________________________________________________
dockmoor [OPTIONS] <link:#contains-command[contains] | link:#list-command[list]> [command-OPTIONS]
__________________________________________________________________________________________________

[[_application_options]]
Application Options
-------------------

**-l**, *--log-level* Sets the log-level (one of `NONE`, `ERROR`, `WARN`, `INFO`, `DEBUG`)

*--version* Show version and exit

[[_commands]]
Commands
~~~~~~~~

* link:#contains-command[contains]
* link:#list-command[list]

[[_contains_command]]
contains command
^^^^^^^^^^^^^^^^

________________________________________________________
dockmoor [OPTIONS] contains [contains-OPTIONS] InputFile
________________________________________________________

Test if a file contains image references with matching predicates. Returns exit code 0 when the given input contains at least one image reference that satisfy the given conditions and is of valid format, non-null otherwise

[[_domain_predicates]]
Domain Predicates
~~~~~~~~~~~~~~~~~

Limit matched image references depending on their domain

*--domain* Matches all images matching one of the specified domains

[[_name_predicates]]
Name Predicates
~~~~~~~~~~~~~~~

Limit matched image references depending on their name

*--name* Matches all images matching one of the specified names (e.g. "docker.io/library/nginx")

**-f**, *--familiar-name* Matches all images matching one of the specified familiar names (e.g. "nginx")

*--path* Matches all images matching one of the specified paths (e.g. "library/nginx")

[[_tag_predicates]]
Tag Predicates
~~~~~~~~~~~~~~

Limit matched image references depending on their tag

*--untagged* Matches images with no tag

*--latest* Matches images with latest or no tag. References with digest are only matched when explicit latest tag is present.

*--tag* Matches all images matching one of the specified tag

[[_digest_predicates]]
Digest Predicates
~~~~~~~~~~~~~~~~~

Limit matched image references depending on their digest

*--unpinned* Matches unpinned image references, i.e. image references without digest.

*--digest* Matches all image references with one of the provided digests

[[_list_command]]
list command
^^^^^^^^^^^^

________________________________________________
dockmoor [OPTIONS] list [list-OPTIONS] InputFile
________________________________________________

List image references with matching predicates. Returns exit code 0 when the given input contains at least one image reference that satisfy the given conditions and is of valid format, non-null otherwise

[[_domain_predicates_2]]
Domain Predicates
~~~~~~~~~~~~~~~~~

Limit matched image references depending on their domain

*--domain* Matches all images matching one of the specified domains

[[_name_predicates_2]]
Name Predicates
~~~~~~~~~~~~~~~

Limit matched image references depending on their name

*--name* Matches all images matching one of the specified names (e.g. "docker.io/library/nginx")

**-f**, *--familiar-name* Matches all images matching one of the specified familiar names (e.g. "nginx")

*--path* Matches all images matching one of the specified paths (e.g. "library/nginx")

[[_tag_predicates_2]]
Tag Predicates
~~~~~~~~~~~~~~

Limit matched image references depending on their tag

*--untagged* Matches images with no tag

*--latest* Matches images with latest or no tag. References with digest are only matched when explicit latest tag is present.

*--tag* Matches all images matching one of the specified tag

[[_digest_predicates_2]]
Digest Predicates
~~~~~~~~~~~~~~~~~

Limit matched image references depending on their digest

*--unpinned* Matches unpinned image references, i.e. image references without digest.

*--digest* Matches all image references with one of the provided digests

[[_building_locally_and_contributing]]
Building locally and Contributing
---------------------------------

Appreciated! See link:CONTRIBUTING.md[CONTRIBUTING] for details.

[[_roadmap]]
Roadmap
-------

Currently dockmoor is in a very eraly stage and under constant development.

To get an idea where the journey will go, take a look at the link:ROADMAP.md[Roadmap]

