
:branch: master

== dockmoor
image:https://img.shields.io/circleci/project/github/MeneDev/dockmoor/{branch}.svg[Build Status (Circle CI), link=https://circleci.com/gh/MeneDev/dockmoor]
image:https://img.shields.io/coveralls/github/MeneDev/dockmoor/{branch}.svg[Coveralls statement coverage, link=https://coveralls.io/github/MeneDev/dockmoor]
image:https://img.shields.io/twitter/follow/MeneDev.svg?style=social&label=%40MeneDev[Follow @MeneDev on Twitter, link=https://twitter.com/MeneDev]

Manage docker image references.

[[_examples]]
Examples
--------

[[contains-command-examples]]
contains command
~~~~~~~~~~~~~~~~

[[_use_unix_find_to_list_all_files_containing_unpinned_references]]
Use unix find to list all files containing unpinned references
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,bash]
----
find some-folder/ -type f -exec dockmoor contains --unpinned {} \; -print
----

stdout:

_____________________________________________
....
some-folder/Dockerfile-nginx-untagged
some-folder/subfolder/Dockerfile-nginx-latest
some-folder/Dockerfile-nginx-1.15.3
some-folder/Dockerfile-nginx-latest
....
_____________________________________________

stderr is empty +
exit code: 0

[[_use_unix_find_to_list_all_files_containing_latestno_tags]]
Use unix find to list all files containing latest/no tags
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,bash]
----
find some-folder/ -type f -exec dockmoor contains --latest {} \; -print
----

stdout:

_____________________________________________
....
some-folder/Dockerfile-nginx-untagged
some-folder/subfolder/Dockerfile-nginx-latest
some-folder/Dockerfile-nginx-latest
....
_____________________________________________

stderr is empty +
exit code: 0

[[_use_unix_find_to_list_all_supported_files]]
Use unix find to list all supported files
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[source,bash]
----
find some-folder/ -type f -exec dockmoor contains --any {} \; -print
----

stdout:

_____________________________________________
....
some-folder/Dockerfile-nginx-tagged-digest
some-folder/Dockerfile-nginx-untagged
some-folder/subfolder/Dockerfile-nginx-latest
some-folder/Dockerfile-nginx-1.15.3
some-folder/Dockerfile-nginx-digest
some-folder/Dockerfile-nginx-latest
....
_____________________________________________

stderr is empty +
exit code: 0

[[_test_the_format_of_a_file]]
Test the format of a file
^^^^^^^^^^^^^^^^^^^^^^^^^

The `contains` command returns with exit code 0 when an image reference was found that matches. Using the `--any` predicate allows to match any file with a supported format that contains at least one image reference.

[source,bash]
----
dockmoor contains --any some-folder/Dockerfile-nginx-latest
----

stdout is empty +
stderr is empty +
exit code: 0

[source,bash]
----
dockmoor contains --any some-folder/NotADockerfile
----

stdout is empty +
stderr is empty +
exit code: 4

[[_supported_formats]]
Supported Formats
-----------------

* Dockerfile (as used by `docker build`)

[[_usage]]
Usage
-----

_______________________________________________________________________
dockmoor [OPTIONS] <link:#contains-command[contains]> [command-OPTIONS]
_______________________________________________________________________

[[_application_options]]
Application Options
-------------------

**-l**, *--log-level* Sets the log-level (one of `NONE`, `ERROR`, `WARN`, `INFO`, `DEBUG`)

*--version* Show version and exit

*--manpage* Show man page and exit

*--markdown* Show usage as markdown and exit

*--asciidoc-usage* Show usage as asciidoc and exit

[[_help_options]]
Help Options
------------

**-h**, *--help* Show this help message

[[_commands]]
Commands
~~~~~~~~

* link:#contains-command[contains]

[[_contains_command]]
contains command
^^^^^^^^^^^^^^^^

________________________________________________________
dockmoor [OPTIONS] contains [contains-OPTIONS] InputFile
________________________________________________________

Returns exit code 0 when the given input contains at least one image reference that satisfy the given conditions, non-null otherwise

[[_predicates]]
Predicates
~~~~~~~~~~

Specify which kind of image references should be selected. Exactly one must be specified

*--any* Matches all images

*--latest* Matches images with latest or no tag

[[_help_options_2]]
Help Options
~~~~~~~~~~~~

**-h**, *--help* Show this help message

