[#list-command-examples]
=== list command
All single file examples refer to https://github.com/MeneDev/dockmoor/blob/master/cmd/dockmoor/end-to-end/Dockerfile[a multi-stage build Dockerfile]

==== List all image references where the tag ends in `-test`

Surrounding strings with `/` enables regular expression based matching.
[subs=+macros]
----
include::../end-to-end/test.sh[tag=listTagsWithRegexMatch,indent=0]
----
stdout:
----
include::../end-to-end/results/listTagsWithRegexMatch.stdout[indent=0]
----
stderr is empty +
exit code:
include::../end-to-end/results/listTagsWithRegexMatch.exitCode[]

==== List all image references with latest or no tag from a specific domain in file

You can use multiple predicates to filter the matching image references.
In this example the `domain` predicate is used together wih the `latest` predicate.
Predicates are connected to a `conjunction`: all predicates must match.

[subs=+macros]
----
include::../end-to-end/test.sh[tag=listDomainWithLatestInFile,indent=0]
----
stdout:
----
include::../end-to-end/results/listDomainWithLatestInFile.stdout[indent=0]
----
stderr is empty +
exit code:
include::../end-to-end/results/listDomainWithLatestInFile.exitCode[]

==== List all image references in file

[subs=+macros]
----
include::../end-to-end/test.sh[tag=listAnyInFile,indent=0]
----
stdout:
----
include::../end-to-end/results/listAnyInFile.stdout[indent=0]
----
stderr is empty +
exit code:
include::../end-to-end/results/listAnyInFile.exitCode[]


==== List all image references with latest or no tag in file
[subs=+macros]
----
include::../end-to-end/test.sh[tag=listLatestInFile,indent=0]
----
stdout:
----
include::../end-to-end/results/listLatestInFile.stdout[indent=0]
----
stderr is empty +
exit code:
include::../end-to-end/results/listLatestInFile.exitCode[]


==== List all unpinned image references
[subs=+macros]
----
include::../end-to-end/test.sh[tag=listUnpinnedInFile,indent=0]
----
stdout:
----
include::../end-to-end/results/listUnpinnedInFile.stdout[indent=0]
----
stderr is empty +
exit code:
include::../end-to-end/results/listUnpinnedInFile.exitCode[]


==== Use unix find to list all unpinned image references
[subs=+macros]
----
include::../end-to-end/test.sh[tag=listUnpinnedInFolder,indent=0]
----
stdout:
----
include::../end-to-end/results/listUnpinnedInFolder.stdout[indent=0]
----
stderr is empty +
exit code:
include::../end-to-end/results/listUnpinnedInFolder.exitCode[]


==== Use unix find to list all image references with latest/no tags
[subs=+macros]
----
include::../end-to-end/test.sh[tag=listLatestInFolder,indent=0]
----
stdout:
----
include::../end-to-end/results/listLatestInFolder.stdout[indent=0]
----
stderr is empty +
exit code:
include::../end-to-end/results/listLatestInFolder.exitCode[]


==== Use unix find to list all image references
[subs=+macros]
----
include::../end-to-end/test.sh[tag=listAnyInFolder,indent=0]
----
stdout:
----
include::../end-to-end/results/listAnyInFolder.stdout[indent=0]
----
stderr is empty +
exit code:
include::../end-to-end/results/listAnyInFolder.exitCode[]

