[#pin-command-examples]
=== pin command

The `pin` command queries a Docker daemon (local or remote)
for images matching the used image references and tries to
choose the most precise one.

Note: the Docker daemon only knows pulled images!
Future dockmoor versions will be able to query repositories, too.

==== Pin well-known image references by tag only

Add missing tags and update tags to the most strict version.

[subs=+macros]
----
include::../end-to-end/test.sh[tag=pinNginxNoDigestWithDockerd]
----
File before execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-nginx.org[]
----


File after execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-nginx-any-no-digest.expected[]
----
stdout is empty +
stderr is empty +
exit code:
include::../end-to-end/results/pinNginxWithDockerd.exitCode[]


==== Pin well-known image references by tag and digest

This is the default and recommended format:
the version conveys semantic information,
the digest ensures immutability.

[subs=+macros]
----
include::../end-to-end/test.sh[tag=pinNginxWithDockerd]
----
File before execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-nginx.org[]
----
File after execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-nginx-any.expected[]
----
stdout is empty +
stderr is empty +
exit code:
include::../end-to-end/results/pinNginxWithDockerd.exitCode[]


==== Pin all image references in a dockerfile

[subs=+macros]
----
include::../end-to-end/test.sh[tag=pinWithDockerd]
----
File before execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-testimagea[]
----
File after execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-testimagea-any.expected[]
----
stdout is empty +
stderr is empty +
exit code:
include::../end-to-end/results/pinWithDockerd.exitCode[]

==== Pin image references with latest or no tag in a dockerfile

[subs=+macros]
----
include::../end-to-end/test.sh[tag=pinLatestWithDockerd]
----
File before execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-testimagea[]
----
File after execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-testimagea-latest.expected[]
----
stdout is empty +
stderr is empty +
exit code:
include::../end-to-end/results/pinLatestWithDockerd.exitCode[]
