[#pin-command-examples]
=== pin command

The `pin` command queries a Docker daemon (local or remote)
for images matching the used image references and tries to
choose the most precise one.

*Note* the Docker daemon only knows pulled images! +
Future dockmoor versions will be able to query repositories, too.

==== Pin well-known image references by tag only

Add missing tags and update tags to the most strict version.

[subs=+macros]
----
include::../end-to-end/test.sh[tag=pinNginxNoDigestWithDockerd]
----

Given the following multi-stage dockerfile:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-nginx.org[]
----

We can see that `nginx` employs a widely used tagging strategy: the tags `1` and `1.15` are updated when `1.15.6` is published.
All three tags refer to the same image until `1.15.7` is published. +
Additionally different **variants** are separated from the version by a hyphen.

Executing the command will change the file to:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-nginx-any-no-digest.expected[]
----

Tags are only changed when a more strict version is found that referrers to the *exact same* image.
The `pin` command will never try to update tags to a different (e.g. later) version.

In this example `1.15.6` refers to the same image as `1` and `1.15`. +
However, `1.15-alpine-perl` referred to the `1.15.5-alpine-perl`.

This example uses the `--no-digest` flag to pin image references by tag only.
While tags are the way we usually address different image versions,
we'll learn in the next example that there is a better way.

Other properties of the command: +
stdout is empty +
stderr is empty +
exit code:
include::../end-to-end/results/pinNginxWithDockerd.exitCode[]


==== Pin well-known image references by tag and digest

Pinning image references by tag, like we did in the previous example, helps creating more reproducible builds.
However, as we also saw in the previous example, tags can be overwritten!

Fortunately dockmoor allows us to use tags and digests to pin our images.

Digests are a direct result of the actual content of the images and thus cannot be overwritten.

This is the default and recommended format:
the version conveys semantic information,
the digest ensures immutability.

[subs=+macros]
----
include::../end-to-end/test.sh[tag=pinNginxWithDockerd]
----

File after execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-nginx-any.expected[]
----

stdout is empty +
stderr is empty +
exit code:
include::../end-to-end/results/pinNginxWithDockerd.exitCode[]


==== Pin all image references in a dockerfile

[subs=+macros]
----
include::../end-to-end/test.sh[tag=pinWithDockerd]
----

File before execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-testimagea[]
----

File after execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-testimagea-any.expected[]
----

stdout is empty +
stderr is empty +
exit code:
include::../end-to-end/results/pinWithDockerd.exitCode[]

==== Pin image references with latest or no tag in a dockerfile

[subs=+macros]
----
include::../end-to-end/test.sh[tag=pinLatestWithDockerd]
----

File after execution:
[source,Dockerfile]
----
include::../end-to-end/pin-examples/Dockerfile-testimagea-latest.expected[]
----

stdout is empty +
stderr is empty +
exit code:
include::../end-to-end/results/pinLatestWithDockerd.exitCode[]
