== Usage
> ___go_build_00_main_go_cmd_find_go_exit_codes_go_asciidoc_go_markdown_go [OPTIONS] &lt;<<find-command,find>>&gt; [command-OPTIONS]

## Application Options
**-l**, **--log-level**
Sets the log-level (one of `NONE`, `ERROR`, `WARN`, `INFO`, `DEBUG`)

**--version**
Show version and exit

**--manpage**
Show man page and exit

**--markdown**
Show usage as markdown and exit

**--asciidoc-usage**
Show usage as asciidoc and exit

## Help Options
**-h**, **--help**
Show this help message

=== Commands

 * <<find-command,find>>

==== find command
> ___go_build_00_main_go_cmd_find_go_exit_codes_go_asciidoc_go_markdown_go [OPTIONS] find [find-OPTIONS] InputFile

The find command returns exit code 0 when the given input contains at least one image reference that satisfy the given conditions, non-null otherwise

### Predicates
Specify which kind of image references should be selected. Exactly one must be specified

**--any**
Find all images

### Help Options
**-h**, **--help**
Show this help message