name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  create:
    tags:
      - v*

jobs:
  build:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1